"""Initial schema

Revision ID: ef1c9a3114b9
Revises: 
Create Date: 2026-04-10 10:43:26.812557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1c9a3114b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_table('daily_pnl',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('ending_balance', sa.Float(), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date')
    )
    op.create_table('kill_switch_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_reason', sa.Text(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id = 1', name='singleton_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_timestamp'), 'portfolio_snapshots', ['timestamp'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pred_len', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('predicted_close_mean', sa.Float(), nullable=False),
    sa.Column('predicted_close_std', sa.Float(), nullable=False),
    sa.Column('predicted_high_mean', sa.Float(), nullable=False),
    sa.Column('predicted_low_mean', sa.Float(), nullable=False),
    sa.Column('current_price_at_prediction', sa.Float(), nullable=False),
    sa.Column('actual_close', sa.Float(), nullable=True),
    sa.Column('prediction_error', sa.Float(), nullable=True),
    sa.Column('raw_predictions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predictions_predicted_at', 'predictions', ['predicted_at'], unique=False)
    op.create_index('idx_predictions_symbol', 'predictions', ['symbol'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('net_edge', sa.Float(), nullable=False),
    sa.Column('predicted_close', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    op.create_index('idx_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_index('idx_signals_symbol', 'signals', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('notional_value', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('alpaca_order_id', sa.String(length=64), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('idx_trades_requested_at', 'trades', ['requested_at'], unique=False)
    op.create_index('idx_trades_status', 'trades', ['status'], unique=False)
    op.create_index('idx_trades_symbol', 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_symbol', table_name='trades')
    op.drop_index('idx_trades_status', table_name='trades')
    op.drop_index('idx_trades_requested_at', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_signals_symbol', table_name='signals')
    op.drop_index('idx_signals_created_at', table_name='signals')
    op.drop_table('signals')
    op.drop_index('idx_predictions_symbol', table_name='predictions')
    op.drop_index('idx_predictions_predicted_at', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolio_snapshots_timestamp'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_table('kill_switch_state')
    op.drop_table('daily_pnl')
    op.drop_index('idx_audit_event_type', table_name='audit_log')
    op.drop_index('idx_audit_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
