from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Literal
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class Side(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"


class AssetClass(str, Enum):
    STOCK = "stock"
    CRYPTO = "crypto"
    ETF = "etf"


class Timeframe(str, Enum):
    DAILY = "daily"
    HOURLY = "hourly"


# --- Agent -> Execution Service ---


class TradeRequest(BaseModel):
    """Sent from the agent to the execution service."""

    request_id: UUID = Field(default_factory=uuid4)
    symbol: str
    asset_class: AssetClass
    side: Side
    order_type: OrderType = OrderType.MARKET
    quantity: float = Field(gt=0)  # Shares (fractional allowed)
    notional_value: float = Field(gt=0)  # Dollar value of the trade
    limit_price: float | None = None  # Required if order_type is LIMIT
    signal_id: UUID
    expected_return: float
    confidence: float = Field(ge=0.0, le=1.0)
    timeframe: Timeframe
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class TradeResponse(BaseModel):
    """Returned from the execution service."""

    request_id: UUID
    status: Literal["accepted", "rejected", "error"]
    order_id: str | None = None
    rejection_reason: str | None = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# --- Kronos Predictions ---


class PredictionResult(BaseModel):
    """Output from the Kronos prediction service for a single symbol."""

    symbol: str
    timeframe: Timeframe
    predicted_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    pred_len: int
    sample_count: int

    # Ensemble statistics for each predicted step (lists of length pred_len)
    mean_close: list[float]
    std_close: list[float]
    mean_high: list[float]
    mean_low: list[float]

    # Per-sample predicted close for the first future step (for ensemble analysis)
    sample_closes: list[float] = Field(default_factory=list)


# --- Signal Engine ---


class Signal(BaseModel):
    """Generated by the signal engine when an edge is detected."""

    signal_id: UUID = Field(default_factory=uuid4)
    symbol: str
    asset_class: AssetClass
    side: Side
    timeframe: Timeframe
    current_price: float
    predicted_close: float  # Ensemble mean close at first prediction step
    expected_return: float
    expected_volatility: float
    confidence: float = Field(ge=0.0, le=1.0)
    ensemble_std: float
    net_edge: float
    suggested_quantity: float = Field(gt=0)
    notional_value: float = Field(gt=0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# --- Position Data ---


class Position(BaseModel):
    """A position in a single instrument."""

    symbol: str
    asset_class: AssetClass
    side: Side
    quantity: float
    avg_entry_price: float
    current_price: float | None = None
    market_value: float = 0.0
    unrealized_pnl: float = 0.0


class RiskStatus(BaseModel):
    """Current risk utilization."""

    kill_switch_active: bool
    portfolio_value: float
    max_position_dollars: int
    current_position_dollars: float
    position_utilization: float
    max_daily_loss_dollars: int
    current_daily_loss_dollars: float
    loss_utilization: float
    crypto_allocation_pct: float
    max_crypto_pct: float
    worst_concentration_symbol: str | None = None
    worst_concentration_pct: float = 0.0
    max_concentration_pct: float
    trades_this_hour: int
    max_trades_per_hour: int
